host=10.203.221.16
port=4181
tls=no
wait=20
vdev_min=181
vdev_max=184
certificate="/root/cert.pem"
key_file =  "/root/key.pem"
ca_file =   "/root/ca.pem"
retention_default=7
retention_max=1200
ebcdic_codepage=IBM037
iucv_userid=maint740
iucv=yes
